const TOKEN = "lgosgsdfsagds";

const AUTH_REQUEST = "AUTH_REQUEST";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";

const GOOGLE_AUTH_REQUEST = "GOOGLE_AUTH_REQUEST";
const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";

const USER_MESSAGES_REQUEST = "USER_MESSAGES_REQUEST";
const USER_MESSAGES_SUCCESS = "USER_MESSAGES_SUCCESS";
const USER_MESSAGES_FAIL = "USER_MESSAGES_FAIL";

const GET_ALL_USERS_REQ = "GET_ALL_USERS_REQ";
const GET_ALL_USERS_SUC = "GET_ALL_USERS_SUC";
const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export {
  TOKEN,
  AUTH_REQUEST,
  AUTH_SUCCESS,
  AUTH_FAIL,
  GOOGLE_AUTH_REQUEST,
  GOOGLE_AUTH_SUCCESS,
  GOOGLE_AUTH_FAIL,
  USER_MESSAGES_REQUEST,
  USER_MESSAGES_SUCCESS,
  USER_MESSAGES_FAIL,
  GET_ALL_USERS_REQ,
  GET_ALL_USERS_SUC,
  GET_ALL_USERS_FAIL,
};
